In [1]:
"""module docstring"""
from itertools import permutations
import csv
from typing import List, Dict
from fractions import Fraction as Ratio
from random import randint, sample

import pandas as pd
import numpy as np
import altair as alt

from altair import Chart
Dat = pd.DataFrame

from entities import Bet, Competitor, Forecaster, Game
from boards import Boards
from book import Book
from utils import show

from demo import trn

#dir(trn)

In [2]:
trn.players_df

                  score
Austin Cole         2.0
Chris Schröder      1.5
Crawford Collins    4.5
Daniel Harris       3.5
Huthman King        1.5
Mychal Hall         3.5
Pierre Damiba       2.0
Ray Lomeli          0.5
Ryan Allred         2.5
Scott Schindler     0.5
Troy Bradley        1.5
Zach Angell         3.5

In [10]:
trn.games_df.applymap(show)

                black             white            winner
1       Daniel Harris  Crawford Collins     Daniel Harris
2       Daniel Harris   Scott Schindler     Daniel Harris
3        Troy Bradley    Chris Schröder      Troy Bradley
4         Austin Cole       Mychal Hall       Austin Cole
5       Daniel Harris    Chris Schröder     Daniel Harris
6         Austin Cole   Scott Schindler       Austin Cole
7         Austin Cole  Crawford Collins       Austin Cole
8       Pierre Damiba        Ray Lomeli     Pierre Damiba
9       Pierre Damiba       Ryan Allred     Pierre Damiba
10       Troy Bradley      Huthman King              draw
11        Mychal Hall  Crawford Collins              draw
12     Chris Schröder     Pierre Damiba              draw
13        Mychal Hall       Ryan Allred              draw
14        Ryan Allred     Pierre Damiba              draw
15      Pierre Damiba      Huthman King              draw
16       Huthman King        Ray Lomeli              draw
17        Zach Angell       Austin Cole              draw
18        Ryan Allred       Mychal Hall              draw
19   Crawford Collins     Pierre Damiba     Pierre Damiba
20       Troy Bradley  Crawford Collins  Crawford Collins
21         Ray Lomeli       Zach Angell       Zach Angell
22      Daniel Harris       Ryan Allred       Ryan Allred
23   Crawford Collins      Huthman King      Huthman King
24     Chris Schröder        Ray Lomeli        Ray Lomeli
25      Pierre Damiba       Mychal Hall       Mychal Hall
26      Daniel Harris        Ray Lomeli        Ray Lomeli
27      Pierre Damiba   Scott Schindler   Scott Schindler
28        Mychal Hall      Huthman King            NOBODY
29        Mychal Hall       Austin Cole            NOBODY
30    Scott Schindler       Zach Angell            NOBODY
..                ...               ...               ...
103        Ray Lomeli      Huthman King            NOBODY
104    Chris Schröder  Crawford Collins            NOBODY
105  Crawford Collins      Troy Bradley            NOBODY
106      Huthman King       Ryan Allred            NOBODY
107      Huthman King     Pierre Damiba            NOBODY
108    Chris Schröder       Zach Angell            NOBODY
109    Chris Schröder     Daniel Harris            NOBODY
110      Troy Bradley     Pierre Damiba            NOBODY
111      Huthman King      Troy Bradley            NOBODY
112       Zach Angell       Ryan Allred            NOBODY
113       Ryan Allred   Scott Schindler            NOBODY
114     Pierre Damiba       Austin Cole            NOBODY
115     Daniel Harris       Mychal Hall            NOBODY
116       Ryan Allred     Daniel Harris            NOBODY
117     Pierre Damiba  Crawford Collins            NOBODY
118       Mychal Hall       Zach Angell            NOBODY
119      Huthman King    Chris Schröder            NOBODY
120        Ray Lomeli       Austin Cole            NOBODY
121       Austin Cole        Ray Lomeli            NOBODY
122     Pierre Damiba      Troy Bradley            NOBODY
123     Pierre Damiba       Zach Angell            NOBODY
124   Scott Schindler       Austin Cole            NOBODY
125       Austin Cole     Pierre Damiba            NOBODY
126      Troy Bradley     Daniel Harris            NOBODY
127       Ryan Allred       Zach Angell            NOBODY
128       Austin Cole    Chris Schröder            NOBODY
129       Austin Cole     Daniel Harris            NOBODY
130       Ryan Allred       Austin Cole            NOBODY
131     Pierre Damiba    Chris Schröder            NOBODY
132       Mychal Hall      Troy Bradley            NOBODY

[132 rows x 3 columns]

In [4]:
trn.bettors_df

          balance    username
HOUSE      1000.0  @DUMMYNAME
angela      100.0     @angela
hermione    100.0  @DUMMYNAME
dma         100.0        @dma

In [5]:
trn.book_df.applymap(show)

               posted_by odds                on  amount           taken_by
47017      (HOUSE, 1000)  1:1       Austin Cole       2        (NOBODY, 0)
22405      (HOUSE, 1000)  1:1    Chris Schröder       2        (NOBODY, 0)
93610      (HOUSE, 1000)  1:1  Crawford Collins       2        (NOBODY, 0)
68699      (HOUSE, 1000)  1:1     Daniel Harris       2        (NOBODY, 0)
20527      (HOUSE, 1000)  1:1      Huthman King       2        (NOBODY, 0)
31897      (HOUSE, 1000)  1:1       Mychal Hall       2        (NOBODY, 0)
61338      (HOUSE, 1000)  1:1     Pierre Damiba       2  (hermione, 100.0)
48040      (HOUSE, 1000)  1:1        Ray Lomeli       2  (hermione, 100.0)
74210      (HOUSE, 1000)  1:1       Ryan Allred       2       (dma, 100.0)
29673      (HOUSE, 1000)  1:1   Scott Schindler       2        (NOBODY, 0)
72465      (HOUSE, 1000)  1:1      Troy Bradley       2  (hermione, 100.0)
32294      (HOUSE, 1000)  1:1       Zach Angell       2    (angela, 100.0)
82149       (dma, 100.0)  4:1       Ryan Allred       4        (NOBODY, 0)
77848       (dma, 100.0)  9:1      Troy Bradley       1        (NOBODY, 0)
37557  (hermione, 100.0)  3:1     Pierre Damiba       9        (NOBODY, 0)

In [6]:
trn.show_taken_bets()

           posted_by odds             on  amount           taken_by
61338  (HOUSE, 1000)  1:1  Pierre Damiba       2  (hermione, 100.0)
48040  (HOUSE, 1000)  1:1     Ray Lomeli       2  (hermione, 100.0)
74210  (HOUSE, 1000)  1:1    Ryan Allred       2       (dma, 100.0)
72465  (HOUSE, 1000)  1:1   Troy Bradley       2  (hermione, 100.0)
32294  (HOUSE, 1000)  1:1    Zach Angell       2    (angela, 100.0)

In [7]:
trn.get_stake('hermione').applymap(show)

               posted_by odds             on  amount           taken_by
61338      (HOUSE, 1000)  1:1  Pierre Damiba       2  (hermione, 100.0)
48040      (HOUSE, 1000)  1:1     Ray Lomeli       2  (hermione, 100.0)
72465      (HOUSE, 1000)  1:1   Troy Bradley       2  (hermione, 100.0)
37557  (hermione, 100.0)  3:1  Pierre Damiba       9        (NOBODY, 0)

In [9]:
class Expectation: 
    def __init__(self, bk: Book):
        self.book = bk
    
    def calibration(self, forecaster: str, mode: str = "NULL") -> Chart: 
        '''view expected calibration plot for a forecaster. 
        mode argument: if "NULL" then it projects a uniform random outcome, and shows calibration with respect to that outcome. 
        
        if "IWIN" then it projects the outcome where that forecaster won every bet they placed. 
        '''
        assert mode in ['NULL', 'IWIN']
        
    def make_NULL_outcomes():
        pass

In [22]:
class CalibrationViewer: 
    '''view calibration a forecaster's calibration and brier score '''
    def __init__(self, bk: Book, relevant_to_payout: ratio = ratio(1,5), mode: str = "NULL"): 
        self.book = bk
        self.relevant_to_payout = (relevant_to_payout * len(self.book.players_df)).__ceil__()
        self.expectation: bool = any([x=='NOBODY' for x in self.book.games_df.winner.apply(show)])

In [18]:
# for betid in trn.get_stake('hermione').index: 
#     print(trn.bets[betid])


#trn.bets[[int(x) for x in trn.get_stake('hermione').index]]

trn.book_df

,posted_by,odds,on,amount,taken_by
77867,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d977710>,2,<entities.Forecaster object at 0x7f948d977c18>
36334,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d977748>,2,<entities.Forecaster object at 0x7f948d977d68>
93236,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d977780>,2,<entities.Forecaster object at 0x7f948d977eb8>
68812,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d9777b8>,2,<entities.Forecaster object at 0x7f948d97f048>
11025,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d9777f0>,2,<entities.Forecaster object at 0x7f948d97f198>
10645,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d977828>,2,<entities.Forecaster object at 0x7f948d97f2e8>
64882,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d977860>,2,<entities.Forecaster object at 0x7f948d97fba8>
57844,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d977898>,2,<entities.Forecaster object at 0x7f948d97f9b0>
54435,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d9778d0>,2,<entities.Forecaster object at 0x7f948d977b00>
26794,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d977908>,2,<entities.Forecaster object at 0x7f948d97f828>
56639,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d977940>,2,<entities.Forecaster object at 0x7f948d97f978>
90612,<entities.Forecaster object at 0x7f948d9773c8>,1,<entities.Competitor object at 0x7f948d977978>,2,<entities.Forecaster object at 0x7f948d97fac8>
91543,<entities.Forecaster object at 0x7f948d97f9b0>,4,<entities.Competitor object at 0x7f948d9778d0>,4,<entities.Forecaster object at 0x7f948d97fba8>
21371,<entities.Forecaster object at 0x7f948d97f9b0>,9,<entities.Competitor object at 0x7f948d977940>,1,<entities.Forecaster object at 0x7f948d97fba8>
36484,<entities.Forecaster object at 0x7f948d97fba8>,3,<entities.Competitor object at 0x7f948d977860>,9,<entities.Forecaster object at 0x7f94b80428d0>

In [40]:
# alt.Chart(trn.players_df.reset_index()
#          ).mark_bar().encode(
#     x='index:N', 
#     y=alt.Y('score:Q', sort="ascending"),
#     color=alt.condition(
#         alt.datum.score > 3.5,
#         alt.value('orange'), 
#         alt.value('steelblue')
#     )
# ).serve()

# help(alt.Y)

<VegaLite 2 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html

In [5]:
trn.show_scores().serve()

Note: if you're in the Jupyter notebook, Chart.serve() is not the best
      way to view plots. Consider using Chart.display().
You must interrupt the kernel to cancel this command.

Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]

127.0.0.1 - - [02/Mar/2019 15:48:47] "GET / HTTP/1.1" 200 -

stopping Server...